sudo: required
services:
  - docker

before_install:
  - docker build -t zguanchen/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true zguanchen/docker-react npm run test
language: generic