sudo: required
services:
  - docker

before_install:
  - docker build -t zguanchen/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true zguanchen/docker-react npm run test
language: generic
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-113758841170"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"